kind: pipeline
type: kubernetes
name: default

steps:
- name: Deploy Mobbuy-OAuth2
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - kubectl apply -f oauth2-deployment.yaml
