---
kind: Service
apiVersion: v1
metadata:
  name: oauth2-app
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: "cookies"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-name: "mobbuy"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-ttl: "300"
spec:
  type: LoadBalancer
  selector:
    app: oauth2-app
  externalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 3388
      targetPort: 3388
